export const operators = [
  {
    id: 'operator-sky',
    cancellation: 'Weather reschedule available',
    includes: ['Safety briefing', 'Equipment', 'Pickup'],
    license: 'NTA-PKR-1001',
    name: 'Pokhara Sky Adventures',
    price: 9500,
    responseRate: 98,
    safetyRating: 4.8,
    status: 'active',
    valueRating: 4.7,
  },
  {
    id: 'operator-bike',
    cancellation: 'Full refund up to 24 hours before',
    includes: ['Bike', 'Helmet', 'Guide'],
    license: 'NTA-BIKE-031',
    name: 'Valley Bike Guides',
    price: 5900,
    responseRate: 94,
    safetyRating: 4.6,
    status: 'active',
    valueRating: 4.7,
  },
]

export const activities = [
  {
    id: 'paragliding-pokhara',
    area: 'Sarangkot, Gandaki Province',
    bestSeason: 'September to May',
    coordinates: { lat: 28.24, lng: 83.99 },
    description: 'Tandem flight above Phewa Lake with Annapurna views.',
    difficulty: 'Beginner friendly',
    duration: '30 minutes',
    durationDays: 1,
    gallery: ['/images/paragliding.jpg'],
    highlights: ['Panoramic lake views', 'Licensed tandem pilot', 'Weather-based flight checks'],
    image: '/images/paragliding.jpg',
    includedServices: ['Pilot briefing', 'Equipment', 'Pickup'],
    location: 'Pokhara',
    minAge: 12,
    name: 'Paragliding over Fewa Lake',
    operators: [operators[0]],
    popularityScore: 95,
    priceFrom: 9500,
    province: 'Gandaki',
    rating: 4.8,
    reviewCount: 142,
    riskLevel: 'Medium',
    safety: {
      checklist: ['Check weather', 'Wear closed shoes'],
      equipment: 'Harness, helmet, reserve parachute',
      emergencyGuidance: 'Pilot coordinates with landing crew.',
      medicalWarning: 'Avoid with serious heart conditions.',
    },
    safetyScore: 94,
    seasonTags: ['September', 'October', 'March'],
    shortDescription: 'Tandem flight above Pokhara Valley.',
    status: 'active',
    type: 'Paragliding',
  },
  {
    id: 'nagarkot-mountain-biking',
    area: 'Nagarkot to Bhaktapur trail',
    bestSeason: 'October to May',
    coordinates: { lat: 27.72, lng: 85.52 },
    description: 'Guided mountain biking across village trails.',
    difficulty: 'Moderate',
    duration: '5-6 hours',
    durationDays: 1,
    gallery: ['/images/biking.jpeg'],
    highlights: ['Scenic ridge trail', 'Support guide included', 'Helmet and bike check'],
    image: '/images/biking.jpeg',
    includedServices: ['Bike', 'Helmet', 'Guide'],
    location: 'Nagarkot',
    minAge: 13,
    name: 'Nagarkot Mountain Biking',
    operators: [operators[1]],
    popularityScore: 70,
    priceFrom: 5900,
    province: 'Bagmati',
    rating: 4.6,
    reviewCount: 58,
    riskLevel: 'Medium',
    safety: {
      checklist: ['Check brakes', 'Wear helmet'],
      equipment: 'Bike, helmet, gloves',
      emergencyGuidance: 'Guide carries repair kit and first aid.',
      medicalWarning: 'Avoid with recent fractures.',
    },
    safetyScore: 92,
    seasonTags: ['October', 'November', 'March'],
    shortDescription: 'Guided ridge-to-valley bike ride.',
    status: 'active',
    type: 'Mountain Biking',
  },
  {
    id: 'mardi-himal-heli-tour',
    area: 'Pokhara to Mardi Himal viewpoint',
    bestSeason: 'October to April',
    coordinates: { lat: 28.32, lng: 83.9 },
    description: 'Scenic helicopter flight toward Mardi Himal.',
    difficulty: 'Easy',
    duration: '2 hours',
    durationDays: 1,
    gallery: ['/images/heli.jpeg'],
    highlights: ['Mountain landing viewpoint', 'Weather briefing', 'Small-group flight'],
    image: '/images/heli.jpeg',
    includedServices: ['Pilot briefing', 'Weather check'],
    location: 'Pokhara',
    minAge: 6,
    name: 'Mardi Himal Helicopter Tour',
    operators: [
      {
        ...operators[0],
        id: 'operator-heli',
        license: 'CAAN-HEL-214',
        name: 'Pokhara Heli Services',
        price: 42000,
        safetyRating: 4.9,
      },
    ],
    popularityScore: 65,
    priceFrom: 42000,
    province: 'Gandaki',
    rating: 4.9,
    reviewCount: 42,
    riskLevel: 'Medium',
    safety: {
      checklist: ['Confirm visibility', 'Carry ID'],
      equipment: 'Warm layers and sunglasses',
      emergencyGuidance: 'Operator follows aviation authority procedures.',
      medicalWarning: 'Consult a doctor for serious respiratory conditions.',
    },
    safetyScore: 98,
    seasonTags: ['October', 'November', 'April'],
    shortDescription: 'Scenic mountain helicopter flight.',
    status: 'active',
    type: 'Helicopter Tour',
  },
]

export const reviews = [
  {
    id: 'review-1',
    activityId: 'paragliding-pokhara',
    comment: 'Clear safety briefing and good price comparison.',
    createdAt: '2026-07-01T08:00:00.000Z',
    rating: 5,
    safetyRating: 5,
    userName: 'Maya',
    valueRating: 4,
  },
]

export const user = {
  id: 'user-1',
  email: 'user@example.com',
  fullName: 'Test User',
  phone: '9800000000',
  role: 'user',
  status: 'active',
}

export const admin = {
  id: 'admin-1',
  email: 'admin@example.com',
  fullName: 'Admin User',
  phone: '9800000001',
  role: 'admin',
  status: 'active',
}

export const bookings = [
  {
    id: 'booking-1',
    activityId: 'paragliding-pokhara',
    activityName: 'Paragliding over Fewa Lake',
    bookingReference: 'SAB-TEST-001',
    customerEmail: 'user@example.com',
    customerName: 'Test User',
    customerPhone: '9800000000',
    date: '2099-10-10',
    emergencyName: 'Emergency Contact',
    emergencyPhone: '9811111111',
    extras: [],
    operatorId: 'operator-sky',
    operatorName: 'Pokhara Sky Adventures',
    people: 2,
    status: 'Awaiting payment',
    total: 19000,
    userId: 'user-1',
  },
]
